services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/desafio-backend-caixaverso-jvm
    container_name: desafio-app
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:sqlserver://mssql:1433;databaseName=master;integratedSecurity=false;encrypt=false;trustServerCertificate=true;
      QUARKUS_DATASOURCE_USERNAME: sa
      QUARKUS_DATASOURCE_PASSWORD: Quarkus123
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/quarkus
      QUARKUS_OIDC_CLIENT_ID: backend-service
      QUARKUS_OIDC_CREDENTIALS_SECRET: secret
      QUARKUS_OIDC_TOKEN_ISSUER: http://localhost:8081/realms/quarkus
      QUARKUS_HTTP_HOST: 0.0.0.0
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    depends_on:
      mssql:
        condition: service_healthy
        restart: true
      keycloak:
        condition: service_started
        restart: true
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433"
    volumes:
      - db_data:/var/lib/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Quarkus123
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1\" || exit 0" ]
      interval: 10s
      timeout: 5s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
#    entrypoint: [ "/bin/bash", "-c" ]
#    command: >
#      "/opt/keycloak/bin/kc.sh build --health-enabled=true &&
#       /opt/keycloak/bin/kc.sh start --optimized --import-realm"
    command:
      [
        "start-dev",
        "--import-realm"
      ]
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./config/quarkus-realm.json
        target: /opt/keycloak/data/import/quarkus-realm.json
#    healthcheck:
#      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e \"GET /health/ready HTTP/1.1 Host: http://localhost \" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
#      interval: 5s
#      timeout: 5s
#      retries: 30

volumes:
  db_data: {}

